### PR TITLE
New Endpoint users/clients

### PR DESCRIPTION
**Pull request by pierorepp90**
Entering the following information in the body:
-username
-password
-nameAndSurname
-dni
-address
-image

We will obtain the creation of a new user and a new client.

### CODE REVIEW

**Comment by IT-Academy-BCN** [comment]
Nice ! 
The functionality is perfectly working. Thank you :)
Just two little notes:
* In that context(api calls) I don't recommend you to use CamelCase("nameAndSurname") better snake case if you need to split words, f.e: name_and_surname.
* It would be great to avoid DNI/CIF repetition for the future :)

Thank you for your pull request comments, were very helpful to me to check this task. I need too that you put this endpoint information in [API DOCS file](https://docs.google.com/document/d/1mdjl_rGQjKoIicQqrHqbI3JcEGj6gAPG/edit#) , to explain,even better your feature to your frontend partners :) 

Thanks !

**Comment by IT-Academy-BCN** [comment]
Ah ! and please, disable the public(non authenthicated) calls to api/users that aren't POST type. Thanks !

**Comment by IT-Academy-BCN** [comment]
* Avoid creating users with repeated username.

**Comment by pierorepp90** [comment]
It would take a modification in the Runnable file to be able to implement the unique DNs on clients. Or do this at the controller level.
The documentation is pending for tomorrow.
All other points are covered.
Thank you for your comments and feedback.

**Comment by pierorepp90** [comment]
Documentation is ready.

**Pull request merged**
